#!/usr/bin/env bash

DB_FILE="${XDG_DATA_HOME:-$HOME/.local/share}/lutris/pga.db"
USER_APPS="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
TEMPLATE="\
[Desktop Entry]
Type=Application
Name=%NAME
Icon=lutris_%SLUG
Exec=env LUTRIS_SKIP_INIT=1 lutris lutris:rungameid/%ID
TryExec=lutris
Categories=Game
"

error() { echo -e "$@" >&2 && exit 1; }

[ -f "$DB_FILE" ] || error "Could not find $DB_FILE, skipping..."

sql_query="SELECT id,name,slug FROM games WHERE installed=1"
sqlite3 "$DB_FILE" "$sql_query" -separator "$(echo -en "\t")" |
  while read -r line; do
    id="$(cut -f 1 <<< "$line")"
    name="$(cut -f 2 <<< "$line")"
    slug="$(cut -f 3 <<< "$line")"
    file="$USER_APPS/net.lutris.$slug-$id.desktop"
    mkdir -p "$(dirname "$file")"
    sed "s^%ID^$id^g; s^%NAME^$name^g; s^%SLUG^$slug^g" <<< "$TEMPLATE" > "$file"
  done
